### PR TITLE
Update example to Reactabular 8 suite

### PR DESCRIPTION
**Pull request by wmertens**
It is still buggy though:
* When filtering for "xu", you also get rows that don't have "xu" anywhere
* Visibility toggling works but the checkboxes do not update

I made a webpackbin at http://www.webpackbin.com/VJ1MVI1IM but it doesn't work unfortunately.

### CODE REVIEW

**Comment by bebraw** [comment]
> When filtering for "xu", you also get rows that don't have "xu" anywhere

Note that the example filters against the visible parents and their children. So you get exactly matches like this. Feel free to open a more specific issue to discuss this, though.

> Visibility toggling works but the checkboxes do not update

Can you set up a separate issue for this? That sounds like something to fix.

**Comment by wmertens** [comment]
Ah yes, I see now that the filtering is hierarchical, but the hierarchy no longer works.

**Comment by wmertens** [comment]
Scratch that, it works, but it is missing the styling needed to show the collapse arrow.

**Comment by bebraw** [comment]
screenshot 2017-01-12 15 11 14

Which browser are you using? I may have to improve the styling approach. It goes like this (treetabular):

```css
.show-more:after {
  cursor: pointer;
  padding-right: 0.5em;
  content: "\25B8";
  font-size: large;
}
.show-less:after {
  cursor: pointer;
  padding-right: 0.5em;
  content: "\25BE";
  font-size: large;
}
.has-parent:not(.has-children):before {
  padding-right: 0.5em;
  content: "\0007C";
  font-size: large;
}
```

**Comment by wmertens** [comment]
No, the problem is that I didn't have the styles that you have on the reactabular site. I basically tried to make the webpackbin I linked above work.

**Comment by bebraw** [comment]
Ah... Good point. Maybe easy should bundle more styles.

**Pull request merged**
